#ifndef CONSTS_H
#define CONSTS_H

//PALUDE PUTRESCENTE

#define CANE_SELVAGGIO_ID 1
#define GOBLIN_ID 2
#define SCHELETRO_ID 3
#define ORCO_ID 4
#define ACQUITRINO_VELENOSO_ID 5 // TRAPPOLA
#define GENERALE_ORCO_ID 6

//MAGIONE INFESTATA

#define BOTOLA_BUIA_ID 1  //TRAPPOLA
#define PIPISTRELLO_ID 2
#define ZOMBIE_ID 3
#define FANTASMA_ID 4
#define VAMPIRO_SUPERIORE_ID 5
#define DEMONE_CUSTODE_ID 6

//GROTTA DI CRISTALLO

#define STANZA_VUOTA_ID 1  //NULLA
#define CRITALLI_CADENTI_ID 2  //TRAPPOLA
#define PONTE_PERICOLANTE_ID 3  //TRAPPOLA
#define FORZIERE_MISTERIOSO_ID 4  //TRAPPOLA
#define RUPE_SCOSCESA_ID 5  //TRAPPOLA
#define DRAGO_ANTICO_ID 6  //TRAPPOLA



#endif